baseURL = '/'
languageCode = 'en'
defaultContentLanguage = "en"
hasCJKLanguage = true
enableEmoji = true
title = 'Home'
copyright = 'Floyd Li'
theme = 'hugo-theme-itheme'
paginate = 5
[params]
  defaultCover = 'https://www.apple.com.cn/newsroom/images/apple-logo_black.jpg.landing-regular_2x.jpg'
  email = 'ramfrancis3@gmail.com'
  [[params.socialMedia]]
    name = 'Github'
    url = 'https://github.com/teelrabbit'
  [[params.blogroll]]
    name = 'Related-Content'
    url = '/'
